version: '2.1.{build}'

# branches to build
branches:
  # whitelist
  only:
    - master

image:
#- Visual Studio 2015
- Visual Studio 2017

configuration:
- Release
- Debug

platform:
- x64
#- x86

environment:
  matrix:
  - generator: "Visual Studio 15 2017 Win64"
    CMAKE_ARGUMENTS: 
    SLN_FOLDER: cmk_build\Win64

  - generator: "Visual Studio 15 2017 Win64"
    CMAKE_ARGUMENTS: -D CMAKE_SYSTEM_NAME=WindowsStore -D CMAKE_SYSTEM_VERSION=10.0
    SLN_FOLDER: cmk_build\UWP64

# clone directory
clone_folder: c:\projects\diligentengine

install:
  # clone submodules
  - git submodule update --init --recursive

  # Install a recent CMake
  - set CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.1-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

before_build:
  - cd c:\projects\diligentengine
  - cmake %CMAKE_ARGUMENTS% -H. -B%SLN_FOLDER% -G %generator%

build:
  project: c:\projects\diligentengine\%SLN_FOLDER%\DiligentEngine.sln
  verbosity: normal
  parallel: true
