name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linux -> Android-ARM32-ARM64

    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Java 8
      if: success()
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build with Gradle
      if: success()
      run: |
        cd $GITHUB_WORKSPACE/DiligentSamples/Android
        chmod +x gradlew
        ./gradlew buildDebug
